# Generated by Django 3.2.3 on 2021-05-28 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='cinema.ActorDirector', verbose_name='Актер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='film_director', to='cinema.ActorDirector', verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='cinema.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, to='cinema.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.ratingstar', verbose_name='Звезда'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie', verbose_name='Фильм'),
        ),
    ]
